### PR TITLE
Doomn00b dev

### PR DESCRIPTION
**Pull request by Doomn00b**
Mega-merge!

### CODE REVIEW

**Comment by Doomn00b** [comment]
Many changes, please see the changelog document.

**Comment by cristianoag** [comment]
@Doomn00b - First of all, thanks for your contributions. I was wondering if you think on fitting the scart connector to the cartridge. Don't you think it is too big for it? I can try to squeeze the memories and the V9990 to have it on the top... lets see. I also see you introduced a LMH1980 to derive VSync from CSync... I was looking for that circuit. Thanks! I'll merge the changes and keep routing the V9990 tomorrow.

**Comment by cristianoag** [comment]
Merging changes proposed by @Doomn00b

**Comment by Doomn00b** [comment]
@cristianoag 
Heyo! When I saw your project, I immediately felt the calling - I figure, I'm gonna' enter like darn Cramer in Seinfeld and shout: "ENTER... THE DRAGON!" 😄 Glad you like the changes - and yes, I think it will be difficult to squeeze it in, but I've gotten pretty good in cramped routing - I'm working on something called the Ultra-MSX - you can see my work on the IO-shield there. (here on github) 🙂 I think it can be done, but feel free to remove it in the mean-time - a simple solution is to also make the cartridge taller - we're going to need a custom 3D-print model for the casing anyway, since we'll have connectors running out of it.

I'm going to give routing it a go, asap!

-noob

PS: I'm not getting a registration-email from MSX resource center... :( I'll have to contact them.

**Comment by Doomn00b** [comment]
@cristianoag PS - I made the board a 4-layer, since several of the Chinese PCB-houses have almost the same price for 4-layer as 2-layer, so I figured it was a logical step forward.

**Pull request merged**
